### ISSUE TITLE
Actualizar Tema Som Energia

### ISSUE THREAD

**Issue by blackleg** [Som-Energia/plataforma#108]
Usar tema aalborg como base para el tema de Som Energia.

**Comment by pr3ssh** [comment]
Por propuesta de @blackleg, coordinamos este tema de actualizar el "tema "aquí ;)

**Comment by blackleg** [comment]
@pr3ssh Entiendo que es @spolpen quien se va a encargar de los cambios, no?

**Comment by pr3ssh** [comment]
@blackleg Sí. Él es quien la tiene asignada. Ya la tiene además casi acabada. En breve se subirán los cambios.

**Comment by blackleg** [comment]
@spolpen @pr3ssh Sería conveniente que lo subierais mediante un pull request a la rama devel.

**Comment by spolpen** [comment]
@blackleg Creado el pull request con la adaptación de la plantilla.

**Comment by blackleg** [comment]
@Som-Energia/plataforma 
El [pull request](https://github.com/Som-Energia/plataforma/pull/115) está aceptado en la rama devel para poder probarlo.
Pero habría que corregir algunos detalles. 

- El header con los links de las paginas de Som Energia aparece por debajo de la barra de usuario cuando el usuario está logeado.
- Se podría ocultar o mejorar los estilos de ese header para mantener el web responsive del tema nuevo.

- El formulario de búsqueda que se ha añadido al menú ocupa el sitio donde aparece el menú de login cuando el usuario no esta logeado.

- El formulario de búsqueda se podría eliminar del menú de la plataforma, ya que aparece por defecto en el panel derecho de las paginas. 
En la pantalla principal no aparece pero se podría crear un panel para mostrarlo.

- Revisar los estilos de los botones: [Ver conversación pull](https://github.com/Som-Energia/plataforma/pull/115)

**Comment by spolpen** [comment]
@blackleg Actualizado el pull request con los nuevos cambios.

**Comment by francesccasadella** [comment]
@spolpen se pueden ver ya en plataforma2 ?

**Comment by blackleg** [comment]
@spolpen El pull request esta aceptado en la rama devel

**Comment by spolpen** [comment]
@francesccasadella No están desplegados los cambios aún en plataforma2.
¿@blackleg realizas el despliegue o nos encargamos nosotros?

**Comment by blackleg** [comment]
@spolpen Yo no tengo acceso al servidor. Tendréis que hacerlo vosotros.
Acabo de actualizar la rama stagging con los cambios de devel.  
Tendréis que hacer composer install después de descargar los cambios.

**Comment by spolpen** [comment]
@francesccasadella Ya he realizado el despliegue en plataforma2, por lo que ya podéis comprobar los cambios de la plantilla.
@blackleg He hecho un pequeño commit directamente a stagging por agilizar, ya que en algun merge hemos debido duplicar el topnav y aparecía tanto encima como debajo del menú de los usuarios.
