### ISSUE TITLE
Permitir exportación bbdd mail usuari@s a .csv

### ISSUE THREAD

**Issue by francesccasadella** [Som-Energia/plataforma#11]
Añadir opcion para exportar emails a .csv o .xls usuarios dentro del menú USUARIO del administardor. Atributos: Email + Nombre + Idioma elegido.

**Comment by joseEnrique** [comment]
@francesccasadella he hecho un plugin para que podáis exportar los usuarios desde el admin. Lo subo a stagging, aunque está en este repositorio https://github.com/joseEnrique/export_users_csv . Si quieres funcionalidades extra abre tarea nueva.

**Comment by francesccasadella** [comment]
@joseEnrique plugin revisado y OK a punt para subir a producción.

**Comment by francesccasadella** [comment]
@davidromani a punto para subirlo a stagging y producción
