### ISSUE TITLE
Mover repositorio Som-Energia/Elgg

### ISSUE THREAD

**Issue by blackleg** [Som-Energia/plataforma#114]
@davidromani @francesccasadella ¿Se podría mover este repositorio https://github.com/Som-Energia/Elgg al equipo de la plataforma https://github.com/orgs/Som-Energia/teams/plataforma ?

**Comment by francesccasadella** [comment]
A ver si David R puede comentarlo, o le preguntamos a David Garcia, yo no entiendo la razon, si es para dejarlo más ordenado y puedes hacerlo tu mismo adelante

El 11 maig 2017, a les 10:06, hectorespert <notifications@github.com> va escriure:

**Comment by davidromani** [comment]
@blackleg hecho, creo que és lo que querias, no? He añadido el equipo "plataforma" al repo que comentas...

**Comment by blackleg** [comment]
@davidromani Eso era, muchas gracias.
