### ISSUE TITLE
Fix email notifications with UTF8

### ISSUE THREAD

**Issue by davidromani** [Som-Energia/plataforma#126]
Hay que ajustar los emails enviados a una codificacón de caracteres (UTF8) compatible con todos los sistemas.

<img width="812" alt="captura de pantalla 2017-08-02 a les 8 38 17" src="https://user-images.githubusercontent.com/698779/28860875-a6fde1ec-775e-11e7-9492-04150324ced8.png">

**Comment by blackleg** [comment]
@davidromani Solucionado en la rama devel

**Comment by davidromani** [comment]
ok, se puede mergear en master? o tienes más cosas pendientes?

**Comment by blackleg** [comment]
No hay nada pendiente
