### ISSUE TITLE
Añadir corrector ortográfico en los paneles de texto enriquecido.

### ISSUE THREAD

**Issue by francesccasadella** [Som-Energia/plataforma#13]
Es posible que con añadir el corrector una vez se solucione pero también es posible que haya que ir añadiendo esta mejora en los distintos plugins que hay instalados.

**Comment by pablovg2** [comment]
Hemos añadido el botón de corrector ortográfico en el commit 5bb18b3

**Comment by davidromani** [comment]
hecho

**Comment by francesccasadella** [comment]
@pablovg2 a parte de añadir el botón de corrector ortográfico en el commit, habéis probado una vez a ver si funciona? llevo un rato dandole al botón con el texto seleccionado, sin seleccionar y no hace nada de nada. Toca revisar. 
pd. Si da muchos problemas lo quitamos, no lo veo prioritario, hoy en día ya existen correctores gratuitos disponibles en internet o extensiones por navegadores y sistemas operativos. 
![captura_de_pantalla_2016-01-21_a_les_19_20_26](https://cloud.githubusercontent.com/assets/7600601/12490091/1f330a96-c074-11e5-95f2-7dd16050a481.jpg)
