### ISSUE TITLE
Añadir opción para que los enlaces se abran en una nueva pestaña

### ISSUE THREAD

**Issue by francesccasadella** [Som-Energia/plataforma#131]
en las versiones antiguas había esa funcionalidad, en las ultimas dos versiones ha desaparecido y era bastante util para mejorar la experiencia de las usuarias. 
![captura_de_pantalla_2017-08-08_a_les_17_39_46](https://user-images.githubusercontent.com/7600601/29080707-cc752046-7c60-11e7-96fc-e1cb1dfdf120.jpg)

**Comment by blackleg** [comment]
![insertar_vinculo](https://user-images.githubusercontent.com/4323228/30157855-a88ca2f6-93c3-11e7-982b-af59928793f6.png)
