### ISSUE TITLE
Abrir el Robots.txt

### ISSUE THREAD

**Issue by francesccasadella** [Som-Energia/plataforma#133]
Ahora mismo la plataforma no aparece en google, este fichero no permite ni que se indexen los debates públicos, con todo el potencial que estamos perdiendo con esto:
![captura_de_pantalla_2017-08-08_a_les_17_55_10](https://user-images.githubusercontent.com/7600601/29081490-05a80d18-7c63-11e7-96f7-98e47c6567f7.jpg)

**Comment by blackleg** [comment]
Fixed
