### ISSUE TITLE
Destacar "Comentarios" y aislar "Report this"

### ISSUE THREAD

**Issue by francesccasadella** [Som-Energia/plataforma#15]
Mover la fila de ""Responder, editar, cerrar i me gusta"" debajo de los comentarios y no arriba como esta ahora i ponerlo dentro de una caja. 
Hay gente que le da a "Report this" y escribe ahí la respuesta a un hilo de comentarios.
+INFO: https://www.evernote.com/l/AFPTspJnajpBTYz9-Wvuq3hGMiFGWlocb6o

**Comment by pr3ssh** [comment]
Estamos revisando la forma de separar los enlaces y ponerlos justo después del comentario.
Mientas tanto tenemos una solución para el tema del enlace del *report this* para diferenciarla levemente del resto de enlaces y que no se pulse tan frecuentemente. Qué os parece? (@francesccasadella)

![screen-report](https://cloud.githubusercontent.com/assets/404339/12448624/95bc4004-bf77-11e5-9c52-3736f7638ee7.png)

**Comment by pr3ssh** [comment]
@francesccasadella Por otro lado veo como en Plataforma2 como en la que estamos trabajando actualmente en local (rama devel) el tema de poner destacado el formulario de responder está solucionado. Esta ok pues? Adjunto captura.

![screeen](https://cloud.githubusercontent.com/assets/404339/12453306/f03f8728-bf92-11e5-809b-d234b405b5d9.png)

**Comment by francesccasadella** [comment]
@pr3ssh veo bien la mejora a "Reportar", lo único que no le pondría el color de fondo de más de 30px de alto, para que no destaque tanto y quede integrado en altura con el botón gris de  "subscribe to comment..." (botón que por cierto habría que traducir;). A lo mejor y para evitar la confusión el "Reportar" también se podría alinear a la derecha o centrado en la caja principal (sin contar con el espacio del menú lateral). 

por lo de mover el meú "responder, editar, cerrar..." hacia abajo, yo lo sigo viendo en la parte superior. Si quieres lo aclaramos en la próxima reunión.

**Comment by pr3ssh** [comment]
@francesccasadella El módulo **comment_tracker** está 100% sin traducir. Lo priorizamos para catala, euskera y español?

**Comment by francesccasadella** [comment]
@pr3ssh Si con priorizarlo te refieres a darle preferencia a estos cuatro idiomas del resto de idiomas adelante. Entiendo que esté módulo está 100% por traducir tanto en devel como en máster. Cuando esté a punto me haría falta formación para empezar a traducirlo.

**Comment by pr3ssh** [comment]
@francesccasadella Lo que vamos a hacer es traducir lo básico en los ficheros correspondientes y te pasaré un mensaje para los textos más complejos y buscamos alguien de la comunidad Som que nos eche un cable. Lo paso todo a un nuevo ticket para que se pueda cerrar.

**Comment by francesccasadella** [comment]
@pr3ssh ok

**Comment by francesccasadella** [comment]
@pr3ssh OK, el Galego también debería estar en esa priorización de idioma. 

Castellano, Català, Euskara y Galego.

**Comment by pr3ssh** [comment]
@francesccasadella Ahora mismo creo que no tenemos nada traducido al gallego, verdad?

**Comment by pr3ssh** [comment]
@francesccasadella Sí, perdón. Aquellas del tipo *gl.php*
