### ISSUE TITLE
Subida de archivos con Firefox y Linux

### ISSUE THREAD

**Issue by vokimon** [Som-Energia/plataforma#2]

**Comment by vokimon** [comment]
No puc pujar-ne

**Comment by francesccasadella** [comment]
Solucionar error al subir archivos con el navegador Firefox y Linux. Documentado aquí. SOLUCIÓN: Al tratarse de un caso aislado, hacer Teamviewer o similar con Ana acediendo remotamente a su ordenador para reproducir y solucionar el error
+info: https://plataforma.somenergia.coop/discussion/view/100216/no-puedo-subir-archivos-a-la-plataforma

**Comment by davidromani** [comment]
@francesccasadella seria posible buscar algun momento dentro de la escuela de septiembre para hacer un teamviewer entre su ordenador y el mio?

**Comment by francesccasadella** [comment]
@davidromani ya está solucionado, @monfero le dijo a Ana que era por culpa del Mozilla y que usara el Chrome. Se ve que desde que hace esto ya no tiene el problema.

**Comment by davidromani** [comment]
:+1:

**Comment by francesccasadella** [comment]
reproduzco conversación: 

@monfero comentó en la plataforma: 
No es por tocar las narices pero ... veo que habeis cerrado la incidencia en github pero el caso es que realmente no está solucionado. Lo de tener que cambiarse de navegador para poder subir un archivo es una chapuza. Seguro que no se tomaría la misma decisión si el error estuviese en el formulario de alta de socia, a que no :P

respuesta: 
Buenas Daniel, estuvimos hablando con Ana para solucionarlo en esta escuela de septiembre pero ahora al utilizar Chrome ya no tiene este problema. De todos modos, ya he reabierto el caso, aunque lo más difícil aquí es poder reproducir el error. Seria posible quedar un dia y hora contingo para connectarnos remotamente para reproducirlo y así podemos tratar de solucionarlo al momento? Si no se podria pagar por un servicio tipo BrowserStack, aunque creo que no dan asistencia para Linux y si nos podemos ahorrar este coste pues más que mejor. Saludos!

@monfero comentó:
No se si seré el único raro al que no le funciona (en varios equipos) con Firefox y otros navegadores pero me niego a tener que usar Chrome/Chromiun solo porque no puedo subir archivos con Firefox. Lo miramos cuando quieras.

@pr3ssh @pablovg2  ¿podéis quedar con @monfero para intentar reproducir y solventar el error?

**Comment by pr3ssh** [comment]
Hemos hecho diferentes pruebas de subida de archivos a la plataforma tanto desde Debian como Ubuntu (distribuciones base o hermanas de Mint) y usando la última versión de Firefox (la 43.0) no hemos tenido ningún problema. Además el Firefox en la máquina Debian nos lo hemos bajado desde el repositorio de Mint.
Sin saber exactamente las versiones de navegadores, se recomienda instalar o actualizar de nuevo Firefox. Aquí los comandos usados en Debian aunque en Mint sera mucho más sencillo actualziarlo:

```
Agregar el repo: deb http://packages.linuxmint.com debian import
apt-get update
apt-get install firefox
```

/cc @francesccasadella @monfero

**Comment by francesccasadella** [comment]
avisado a @monfero en la [discusión de la plataforma](https://plataforma.somenergia.coop/discussion/view/100216/no-puedo-subir-archivos-a-la-plataforma) a ver si sigue dandole el error.

**Comment by francesccasadella** [comment]
Problema solucionado con Ubuntu 14.04 y Firefox 43.0 FUNCIONA BIEN :) 

Cierro el issue... Benditas actualizaciones! 

@pr3ssh @pablovg2 @davidromani 

<img width="941" alt="captura de pantalla 2016-03-21 a les 16 55 41" src="https://cloud.githubusercontent.com/assets/7600601/13924805/fcf0e156-ef85-11e5-85b0-17a749569755.png">
