### ISSUE TITLE
Coordinación de mejoras y gestión del presupuesto.

### ISSUE THREAD

**Issue by francesccasadella** [Som-Energia/plataforma#21]
Se requieren voluntarios para coordinar las tareas profesionales, las tareas voluntarias e informar de la situación mensualmente al consejo rector. Incluye gestión del presupuesto actual para mejoras y mantenimiento.

**Comment by davidromani** [comment]
Usa els labels (els tens al menú lateral dret) de Github enlloc de posar-ho entre [ ] ...

**Comment by francesccasadella** [comment]
@davidromani merci, però no trobo cap "label" per especificar si és un issue "Tècnic/No-Tecnic" ni si pertany a grups, fitxers, on the river... estaria bé que Github permetès crear els teus propis labels però no veig que et deixi fer-ho. (com tampoc no et deixa eliminar un "issue" un cop creat) quines coses... :)

**Comment by francesccasadella** [comment]
@davidromani labels puestos! También he asignado los primeros issues a @hasdpk para que pueda empezar ya a trabjar con ellos en cuanto tenga disponibilidad. Hay algunos puntos que pueden suponer más de 10 horas de trabajo que a lo mejor estaria bien comentarlos antes de empezar a trabajar en ellos.

**Comment by davidromani** [comment]
@francesccasadella :+1:
