### ISSUE TITLE
Eliminar Spam en los blogs de la plataforma!

### ISSUE THREAD

**Issue by francesccasadella** [Som-Energia/plataforma#23]
Se estan creando nuevos usuarios en la plataforma que luego hacen publicaciones automaticas en los blogs de la plataforma.  Podéis verlo en: https://plataforma.somenergia.coop/blog/all

**Comment by francesccasadella** [comment]
@pablovg2 @pr3ssh , alguna recomendación? recuerdo que se había comentado la posibilidad de obligar a los nuevos usuarios a poner una foto de perfil para prevenir el spam. Ejemplo spam: 
![captura_de_pantalla_2016-01-21_a_les_20_43_29](https://cloud.githubusercontent.com/assets/7600601/12492587/3a815f2a-c081-11e5-9f05-bffec73eac19.jpg)

**Comment by pr3ssh** [comment]
@francesccasadella Los usuarios que se están creando automáticamente en la Plataforma se están saltando satisfactoriamente el reCAPTCHA del registro?

**Comment by francesccasadella** [comment]
@pr3ssh buena pregunta. No tengo clara la respuesta. Podéis mirar cuando hace que se dio de alta el usuario: https://plataforma.somenergia.coop/profile/bathmatehydropump01 que realizó el comentario de spam: https://plataforma.somenergia.coop/blog/view/136635/official-hydromax-bathmate-hydro-pump-review hace 39 días?  Desde luego el Capcha del formulario de alta hace mucho tiempo que está puesto.

**Comment by pr3ssh** [comment]
@francesccasadella Hemos estado revisando esta issue. Te comento a continuación:

* La versión que tenemos actualmente de Recaptcha es antigua (1.1) y recomiendan el uso de la 1.1.1 que con nuestra versión actual de ELGG no nos permite su instalación.
* Es posible que haya sido un alta aislada debido a que el bot que llevó a cabo dicho alta tenía la imagen casualmente en su bd.

Dada la situación, y como propuesta, dejaría pasar dicha cuestión y si vemos que se convierte no en un caso aislado sino en algo recurrente acometerla dentro de un proceso de actualización global y no parcial.

**Comment by francesccasadella** [comment]
@pr3ssh ok en cerrar el issue por el momento.
