### ISSUE TITLE
Waffle.io

### ISSUE THREAD

**Issue by wtebbens** [Som-Energia/plataforma#24]
Hola companys,

no seria bueno ver todos los issues que gestionamos aqui en github, pero de una forma como Kanban, como lo hace Trello digamos?

Waffle https://waffle.io/ hace precisamente esto, te presenta todo con tarjetas en una especie de kanban dashboard, y lo sincroniza de forma automatica. Creo que podria ser un añadido facil y super util para quien quiere ver que cosas están abiertas etc

un abrazo,

Wouter

**Comment by davidromani** [comment]
@wtebbens estoy de acuerdo contingo, pero la verdad es que hace falta más acción y menos organización. Desde mi punto de vista, tener un equipo resolviendo issues és más prioritario que invertir tiempo en gestión/planificación. Si realmente llega un punto en que gestionar a mucha gente, entoces ya invertiremos tiempo en mejorar la metodologia.

Un saludo compañero :-)

**Comment by wtebbens** [comment]
hola @davidromani, tienes toda la razón. Yo por mi parte estoy un poco desconectado y metido en otras historias. Siendo esta plataforma tan importante, no entiendo que no haya más gente. Espero que vengan más gente a ayudar.
un abrazo!

**Comment by blackleg** [comment]
@Som-Energia/plataforma La cierro para ir limpiando issues abiertas
