### ISSUE TITLE
Sincronización Calendario Plataforma con Google Calendar.

### ISSUE THREAD

**Issue by francesccasadella** [Som-Energia/plataforma#3]
Calendario plataforma: https://plataforma.somenergia.coop/event_calendar/list/ 
Google calendar: https://www.somenergia.coop/es/participa/#calendario

**Comment by davidromani** [comment]
got it

**Comment by blackleg** [comment]
![](http://www.blackleg.es/images/somenergia/calendario.png)

**Comment by blackleg** [comment]
He creado un mod que muestra el google calendar de som energia, creo que esto puede servir.

Faltaría traducir el mod y modificar el css

**Comment by blackleg** [comment]
https://github.com/Som-Energia/plataforma/commit/1c45e1496ec3c60632a326d80ad1b9837ff3b2de

**Comment by francesccasadella** [comment]
Quitamos el calendario de la plataforma y ponemos directamente Google Calendar? Genial! 

Además, con la migración a Google for Work que estamos haciendo con todos los correos de la cooperativa un google calendar bien organizado para cada correo oficial de grupo local tiene mucho más sentido.

**Comment by pablovg2** [comment]
@francesccasadella  Entonces se activa el plugin somenergia_calendar y se desactiva los plugins de calendario de enventos de elgg, Event Calendar 0.85.  Así solo se podrá consultar el calendario de google.
 ¿correcto?

**Comment by francesccasadella** [comment]
@pablovg2 Correcto Pablo. Una duda: ¿ Desactivar plugin = Eliminar la información ? 
Pongamos por caso que en una semana algún grupo local quiere recuperar o consultar el historial de eventos del Event Calendar 0.85, seria posible guardar alguna copia de seguridad con esa información o activar el plug-in para hacer una breve consulta?

**Comment by pablovg2** [comment]
Al desactivar el plugin lo que hace es ocultar la funcionalidad, deshabilitarla de manera que no aparece las opciones de calendario ni se puede consultar la información. 

La información no se borra, al volver activarlo se puede acceder a la información. El problema sería únicamente que si algún grupo quiere consultarlo tendría que notificarlo para que el administrador de la plataforma activara otra vez el plugin, y luego volver a desactivarlo para no mantener los dos al mismo tiempo para no generar confusión.

**Comment by francesccasadella** [comment]
@pablovg2 perfecto pues, adelante con la desactivación del plugin de calendario de eventos para elgg. Entiendo que tu mismo nos avisas y cierras este issue cuando la mejora esté en producción.

**Comment by blackleg** [comment]
Probar el plugin somenergia_calendar antes, por si no es lo que buscabais, ya que es muy basico.

**Comment by francesccasadella** [comment]
@blackleg con que deje hacer un embed del google calendar por ahora seria suficiente ( cc. @pablovg2 ). 
En realidad este google calendar también es provisional porque se están trabajando los nuevos calendarios de google apps con más posibilidades de edición y segmentación (por ejemplo, en el actual no hay posibilidad de filtrar por eventos de un grupo local en concreto)...

**Comment by francesccasadella** [comment]
@pablovg2 como está este tema, por lo que veo ahora hay dos calendarios en la plataforma devel, habría que quitar el de Elgg y poner el Google Calendar en su sitio del menú. Además, las pestañas "Mio" y "Contatos" ahora ya no tienen sentido, no? adjunto captura: 
![captura_de_pantalla_2016-01-21_a_les_16_53_48](https://cloud.githubusercontent.com/assets/7600601/12485777/1118e9a8-c060-11e5-86fd-2a79f962016f.jpg)

**Comment by pr3ssh** [comment]
@francesccasadella Esta hecha nO? Confirmame para cerrarla.

**Comment by francesccasadella** [comment]
@pr3ssh OK, ya se puede cerrar :)
