### ISSUE TITLE
Traducir el módulo comment_tracker

### ISSUE THREAD

**Issue by pr3ssh** [Som-Energia/plataforma#30]
Al menos para el español, el catalán y el vasco (el inglés viene por defecto).

**Comment by francesccasadella** [comment]
@pr3ssh añadiria también el Galego des de buen inicio. Merci

**Comment by francesccasadella** [comment]
Subidos archivos al grupo de traducción: 
[](https://plataforma.somenergia.coop/discussion/view/143452/plataforma-comment-tracker-ayuda-en-la-traduccion-de-ficheros-a-gl-eu-i-ca)

**Comment by francesccasadella** [comment]
@pr3ssh , ya los tienes traducidos y listos para descargar aquí:
https://plataforma.somenergia.coop/file/view/150803/ca-para-revisartxt 
https://plataforma.somenergia.coop/file/view/144346/eu-traducidotxt
https://plataforma.somenergia.coop/file/view/143704/gl-traducidotxt

ojo con la duda sobre el formato del archivo en catalan,
responder a Aina directamente en caso que haga falta.

**Comment by pr3ssh** [comment]
@davidromani  Cerrada la rama y mezclada en *stagging*

**Comment by davidromani** [comment]
Ok, ya lo tenéis subido al entorno de pruebas. Si hay que habilitar o configurar algun plugin vosotros mismos.

El martes haré el merge de stagging a devel.

**Comment by pr3ssh** [comment]
@davidromani @francesccasadella Gracias! No es necesario. Solo con los ficheros ya funciona.
