### ISSUE TITLE
Revisar comentario "perdido" en hilo de discusión. 

### ISSUE THREAD

**Issue by francesccasadella** [Som-Energia/plataforma#32]
hay un debate intenso en la Plataforma pero me da la impresión de que ha colapsado porque este comentario no se puede ver si se sigue la la discusion:

Inicio del mensaje reenviado:

De: noreply@somenergia.coop
Fecha: 3 de febrero de 2016 22:57:59 GMT+01:00
Para: aragonsomenergia@gmail.com
Asunto: Nueva repuesta en el grupo

Iñigo added a new reply to "Re:¿Posibilidad de facturas por correo
postal?" in Comercialització electricitat:

Soy Iñigo y me lanzo a escribir por primera vez. Llevo tiempo leyendo los
comentarios, queriendo entrar a participar y me parece que este es un buen
momento ya que se están comentando cosas muy interesantes y
enriquecedoras, tanto a favor, como en contra de enviar las facturas por
correo.
En mi opinión, habría que buscar una solución a aquellas personas que
solicitan este servicio (por muy minoría que sean y cada vez sean menos)
ya que es un sector más necesitado, aislado, requieren una atención mayor
y se la merecen. Siendo un número pequeño de soci@ s l@s que necesitan de
este método, creo que habría que plantearles a ellos mismos que sistema
creen oportuno, dejando claro que esto supone un importante coste tanto
ecológico como económico.
Entiendo que al pasarse a SOM ENERGIA, estos conceptos no hacen falta ni
ser explicados.
Teniendo en cuenta que a la gente mayor, hablo por mi abuela, le gusta leer
y guardar en papel las facturas, la idea planteada de aprovecharse de los
envíos bancarios es una opción acertada.
Además, se pueden buscar espacios colaboradores con SOM donde se les
impriman sus facturas y puedan pasar a recogerlas, siendo este sistema
una excepción ya que el método factura-papel debe de ser una cosa del
pasado. De esta manera se evita la insostenibilidad del transporte.

View and reply to the discussion:
[https://plataforma.somenergia.coop/view/144412](https://plataforma.somenergia.coop/view/144412)

-------
-------

**Buscando, he encontrado el hilo principal de donde cuelga este comentario:**
[https://plataforma.somenergia.coop/discussion/view/142316/%C2%BFposibilidad-de-facturas-por-correo-postal](https://plataforma.somenergia.coop/discussion/view/142316/%C2%BFposibilidad-de-facturas-por-correo-postal)

![img_8047](https://cloud.githubusercontent.com/assets/7600601/12809872/b114f7a4-cb22-11e5-9dbd-9fdbb726e9d8.PNG)
![unnamed](https://cloud.githubusercontent.com/assets/7600601/12809875/b52cc0d8-cb22-11e5-9ef8-fc8fbbc22ae0.png)

**Comment by pr3ssh** [comment]
@francesccasadella Son dos cosas diferentes verdad? Una es que un comentario parece ser que se ha borrado y otra es que en la página dos de un listado aparecen dos paginadores en lugar de uno. Puede que esté relacionado (o no). Lo miramos.

**Comment by francesccasadella** [comment]
@pr3ssh exactamente, en el primer caso, el comentario es invisible en el [hilo principal](https://plataforma.somenergia.coop/discussion/view/142316/%C2%BFposibilidad-de-facturas-por-correo-postal) aunque sí aparece como respuesta en la [pagina del comentario](https://plataforma.somenergia.coop/view/144412), así como en el módulo "in the river".

**Comment by pr3ssh** [comment]
@francesccasadella No he sido capaz de reproducir el error, qué podemos hacer? Proporcionarme la base de datos de Plataforma por privado para poder dar con la tecla?

**Comment by francesccasadella** [comment]
@pr3ssh adelante, lo pides a @dromani ?

**Comment by pr3ssh** [comment]
Hecho! A la espera...

**Comment by davidromani** [comment]
en breve te llegará por wetransfer (500MB)

**Comment by pr3ssh** [comment]
Ya la tengo descargada. Intento importarla para probarlo lo antes posible. Gracias.

**Comment by pr3ssh** [comment]
@francesccasadella Te quiero comentar una cosa y es que montando el entorno de producción en local para encontrar el error nos han aparecido una serie de errores de código no encontrado de plugins activados. Estos son:

* Crud
* Threads
* Proposals
* Groups operator

Veo que los 3 han sido desarrolllados por las mismas personas. Me puedes comentar el porqué no están en el repo de Github?
Gracias.

**Comment by francesccasadella** [comment]
@pr3ssh no tengo ni idea :(  podemos contactar con esas personas o intentar averiguarlo de alguna otra forma?

**Comment by pr3ssh** [comment]
@davidromani Nos puedes echar un cable en esta tarea? Mira el último comentario que le puse a @francesccasadella. Gracias!

**Comment by francesccasadella** [comment]
@davidromani este issue nos vuelve a dar problemas en los [informes semanales a la plataforma](https://plataforma.somenergia.coop/discussion/view/137348/plan-de-mejoras-en-la-plataforma-2016?offset=10), a ver si podemos avanzar, a parte, falta pasar la rama issue/8 y la rama issue/9 a stagging cuando puedas.

**Comment by pr3ssh** [comment]
Las dos ramas están ya mergeadas en stagging.

@davidromani Nos puedes pasar el código fuente de producción ppara ver si tenemos ésos módulos qeu se solicitan? Es que no somos capaces de reproducir el error ya que nos dice ELGG que faltan algunos módulos.

**Comment by davidromani** [comment]
@francesccasadella @pr3ssh ya he subido al servidor de pruebas el útlimo commit que existe en la rama stagging (https://github.com/Som-Energia/plataforma/commit/62e3fd8adf6f7b268b428bf5c6e1774c9d1104b2)

**Comment by francesccasadella** [comment]
@pr3ssh hemos hablado con @davidromani ahora, hay plugins que tienen la categoría "Git Submodule" y no aparecen en Github, para descargarlos hay que hacerlo desde el servidor. Lo vemos en la reunión de la semana que viene.

**Comment by pr3ssh** [comment]
@francesccasadella @davidromani ack

**Comment by francesccasadella** [comment]
@pr3ssh este tema sigue urgente y los meses van pasando, hay dos usuarios de la plataforma que se han quejado ya de que se pierden los comentarios y no pueden seguir las conversaciones. Sobretodo este debate donde había mucha participación: [https://plataforma.somenergia.coop/discussion/view/142405/que-dependencia-tenemos-de-los-100-e-de-cada-socio](https://plataforma.somenergia.coop/discussion/view/142405/que-dependencia-tenemos-de-los-100-e-de-cada-socio) 

Por favor, intentad darle alguna solución.

**Comment by joseEnrique** [comment]
@francesccasadella Estamos indagando en el asunto. Tenemos el sistema en local y estamos haciendo pruebas y tocando el código. Puede ser por un mal funcionamiento del código o una inconsistencia de datos en la BBDD. Estamos tardando un poco porque la versión de la plataforma es antigua y toda la documentación más nueva es de la 2.x. Esto implica que el motor de la plataforma está modificado casi en su totalidad y hay que buscar funciones de Elgg en su repositorio. Otro problema que estamos teniendo es que el foro lo tienen desactivado para nuevos registros por lo que preguntar a la comunidad es prácticamente imposible, solo se puede si contactas con ellos. Aún no nos han respondido. 

Estamos en proceso. Un saludo

**Comment by francesccasadella** [comment]
Hola @joseEnrique y gracias por informar. En su dia me encontré en lo mismo, pedí permiso y me aceptaron en el foro de Elgg, si quieres hacerme llegar la pregunta la voy publicando. Saludos

**Comment by francesccasadella** [comment]
@joseEnrique como sigue el tema? pudiste preguntar a la comunidad de Elgg?

**Comment by joseEnrique** [comment]
@francesccasadella estamos avanzando. Respecto a la comunidad, me respondió ayer preguntandome que alias quería, espero a ver si me da acceso.

**Comment by joseEnrique** [comment]
Cierro esta tarea. La solución parcial que hemos implantado ha sido eliminar la paginación de la discusión de un hilo del grupo. La cantidad es aceptable para el número de respuesta que tiene cada grupo.

**Comment by blackleg** [comment]
Puede estar relacionado?: https://github.com/lorea/threads/issues/3

**Comment by pr3ssh** [comment]
@blackleg No creo quefuera tanto eso como que cambiaba en paginas con offset algunos comentarios sobre comentarios (2o nivel) por paginadores.

**Comment by blackleg** [comment]
Con respecto a los mods que faltan, en el servidor hay un fichero .gitmodules? Por añadirlo al repositorio, asi tenemos los modulos disponibles.
Si no creo que se pueden obtener los submodulos, desde el fichero config, dentro de .git
