### ISSUE TITLE
Plugin Mobilize

### ISSUE THREAD

**Issue by blackleg** [Som-Energia/plataforma#34]
He encontrado un [plugin](https://elgg.org/plugins/847027) para adaptar esta versión a las pantallas de los móviles.

He creado una nueva rama con el plugin para probarlo. [feature/mobilize](https://github.com/Som-Energia/plataforma/tree/feature/mobilize)

**Comment by francesccasadella** [comment]
@blackleg qué tal los resultados? se podría subir a la plataforma2 para verlo?
