### ISSUE TITLE
Desplegable "Estás Aquí:" por encima del panel de control superior.

### ISSUE THREAD

**Issue by francesccasadella** [Som-Energia/plataforma#4]
+info: https://www.evernote.com/l/AFOQmwiNvYNOM7n55ZwLJliWkBc8Hzm13Ew

**Comment by blackleg** [comment]
![](http://www.blackleg.es/images/somenergia/menu.png) 

Para el próximo merge que haga.

**Comment by blackleg** [comment]
[Solucionado](https://github.com/Som-Energia/plataforma/pull/25)

**Comment by blackleg** [comment]
El código esta en la rama devel de la plataforma, cierro la issue?

**Comment by davidromani** [comment]
@blackleg no, primero tengo que verficar el código en mi instancia local de desarrollo. Y si todo va bien entonces, ya me encargo yo de mergear a master y subir los cambios al entorno de test público. El paso del entorno de test público al entorno de producción tambien lo hago yo.

Un saludo.

**Comment by davidromani** [comment]
@blackleg otra cosa, por favor, para subir código siempre hazlo contra una rama que no sea master. Lo puedes hacer contra devel, o si lo prefieres, en otra rama con tu nombre de usuario. Gracias.

**Comment by davidromani** [comment]
@francesccasadella de momento marco esta issue como solucionado, lo puedes comprobar en https://plataforma2.somenergia.coop/

Cuando lo tenga subido a producción cerraré la issue definitivamente.

**Comment by francesccasadella** [comment]
@davidromani se ve perfecto, good job @blackleg

**Comment by blackleg** [comment]
Que versión de Elgg esta instalada en el servidor  de pruebas?

**Comment by davidromani** [comment]
@blackleg ya tienes un usuario con privilegios de administración, por lo tanto, puedes consultarlo tu mismo aquí https://plataforma2.somenergia.coop/admin/statistics/overview

**Comment by blackleg** [comment]
Hay planes para actualizarla?

**Comment by davidromani** [comment]
Deberiamos subir a la versión 2.0 en cuanto salga de la fase beta. Nos podrás ayudar con la migración?

**Comment by blackleg** [comment]
En lo que pueda ayudaré, según el tiempo que le pueda dedicar.

**Comment by davidromani** [comment]
Ok, gracias.

**Comment by pr3ssh** [comment]
@francesccasadella @davidromani La damos por cerrada?

**Comment by francesccasadella** [comment]
@pr3ssh @davidromani yes! en la plataforma2 se ve perfecto, sólo queda subirla a producción.

**Comment by blackleg** [comment]
:+1:

**Comment by pr3ssh** [comment]
@davidromani La cierras cuando esté hecha para ir limpiando pues ;) (cc @francesccasadella)

**Comment by davidromani** [comment]
ok, el viernes la subo

**Comment by pr3ssh** [comment]
ack

**Comment by blackleg** [comment]
[Algunas mejoras](https://github.com/Som-Energia/plataforma/pull/29)

**Comment by pr3ssh** [comment]
@davidromani Las mejoras de @blackleg incluyen, si no me equivoco, algunas cosas más de las que veníamos comentando no? Si te parece y lo ves correcto, se puede unir el PR y luego cerrar esta tarea si está ok!

**Comment by blackleg** [comment]
Necesitáis ayuda para subir los cambios al servidor?

**Comment by davidromani** [comment]
hecho

**Comment by francesccasadella** [comment]
@davidromani está OK para subir a producción, lástima que en catalan no esté traducido y se vea "You are here" con un "Take part" en vez de participa, a ver si en algun momento alguien puede mostrarme como traducir los literales de la plataforma y lo soluciono. En vez de cerrar el issue, le podríamos poner la etiqueta "Traducción" y "Catalan"? 
<img width="919" alt="captura de pantalla 2016-01-21 a les 20 37 43" src="https://cloud.githubusercontent.com/assets/7600601/12492132/20a392f0-c07f-11e5-918d-3b6db2962b9d.png">

**Comment by blackleg** [comment]
Los archivos con las traducciones se pueden editar desde este enlace: https://github.com/Som-Energia/plataforma/tree/devel/mod/somenergia-theme/languages

**Comment by francesccasadella** [comment]
muchas gracias @blackleg , espero haber realizado mi primer commit en Github correctamente. He aprovechado para hacer un pequeño update en el slogan del header que tenia pendiente desde hace mucho tiempo.  :)

@davidromani OK para subirlo a producción en el próximo lote, añadir label "deployed_on_production" y cerrar el caso. ( @pr3ssh @pablovg2 )

**Comment by pr3ssh** [comment]
Finalizada.
