### ISSUE TITLE
[GoogleSearchConsole] Aviso Error 404

### ISSUE THREAD

**Issue by francesccasadella** [Som-Energia/plataforma#40]
Si accedes a esta URL sin estar logueado en la plataforma: 
[https://plataforma.somenergia.coop/file/download/111995](https://plataforma.somenergia.coop/file/download/111995)
no se puede leer el error que sale en rojo, tendría que aparecer no detrás sino debajo del botón "iniciar sesión".
![2016-07-14 a les 16 57 44](https://cloud.githubusercontent.com/assets/7600601/17030390/8e6df562-4f6f-11e6-96f6-4ea04efb7d9d.png)

**Comment by blackleg** [comment]
https://github.com/Som-Energia/plataforma/pull/44

**Comment by blackleg** [comment]
@joseEnrique @pr3ssh Puedo aceptar el pull request https://github.com/Som-Energia/plataforma/pull/44 y cerrar la issue? Os afectaría?

**Comment by pr3ssh** [comment]
@blackleg No afectaría que yo vea ahora mismo. Esta en devel por lo que veo?

**Comment by blackleg** [comment]
@pr3ssh Ya está en devel, falta que lo probéis y lo paséis a producción.

**Comment by pr3ssh** [comment]
@blackleg Hoy sin falta se sincroniza en master y se sube.
