### ISSUE TITLE
Añadir destacado "Fork Me On Github"

### ISSUE THREAD

**Issue by francesccasadella** [Som-Energia/plataforma#5]
+info: https://github.com/blog/273-github-ribbons

**Comment by blackleg** [comment]
He añadido el fork me on github en el pie de la pagina, quedaria mejor que añadiendo una etiqueta en la esquina, falta formatear el texto para que llame mas la atención.

![](http://www.blackleg.es/images/somenergia/forkme.png)

Pero tengo una duda, actualmente la plataforma muestra estos enlaces: (Acerca de, privacidad, etc)

![](http://www.blackleg.es/images/somenergia/actual.png)

Pero a mi no me los muestra, no se si es alguna modificación que no esta en el repositorio o algún plugin que hay que activar.

**Comment by davidromani** [comment]
@blackleg lo reviso y te digo algo, però si el código es bueno ya te avanzo que lo vamos a mergear seguro.

@hasdpk no hagas nada aquí

**Comment by blackleg** [comment]
De todos los plugins que hay hay en la lista de mods, cuales son los que tenéis activados?

**Comment by blackleg** [comment]
https://github.com/Som-Energia/plataforma/pull/26

**Comment by davidromani** [comment]
@blackleg crea un usuario aquí https://plataforma2.somenergia.coop/ (entorno de test público), me envias el username y te hago admin para que lo puedas gestionar

**Comment by blackleg** [comment]
@davidromani El usuario es Blackleg.

**Comment by davidromani** [comment]
@blackleg hecho, ya puedes administrar los plugins. Déjalos configurados para que pueda ver esta parte.

**Comment by blackleg** [comment]
![](http://www.blackleg.es/images/somenergia/FooterNuevo.png)

A ver que os parece el nuevo footer.

**Comment by davidromani** [comment]
Creo que todas las filas tendrian que tener un alineamiento a la derecha. Además se podria simplificar a 2 filas. Más o menos así:
```
            About | Terms | Privacy
Powered by Elgg | Fork me on GitHub
```

**Comment by blackleg** [comment]
Aquí se ve mejor el footer 
![](http://www.blackleg.es/images/somenergia/otradelfooter.png)

Había pensado dejarlo centrado, pero se puede alienar a la derecha fácilmente.

**Comment by davidromani** [comment]
Mejor a la derecha, por favor. Gracias.

**Comment by blackleg** [comment]
https://github.com/blackleg/plataforma/commit/21d694518ad4174be30f7b83560843dff38f0b44

**Comment by davidromani** [comment]
Puedes alienar todo a la derecha? Gracias
<img width="396" alt="captura de pantalla 2015-11-23 a les 11 27 19" src="https://cloud.githubusercontent.com/assets/698779/11334463/6e6b71ca-91d5-11e5-88a1-09f9636c06ee.png">

**Comment by blackleg** [comment]
Cuando tenga un rato lo miro

**Comment by blackleg** [comment]
https://github.com/Som-Energia/plataforma/pull/27

**Comment by blackleg** [comment]
Ya lo tenéis.

**Comment by davidromani** [comment]
@blackleg gracias
@francesccasadella cierro este issue, ya lo tienes subido en el entorno de pruebas (https://plataforma2.somenergia.coop/)

**Comment by blackleg** [comment]
Cuando tenéis pensado meterlo en producción?

**Comment by francesccasadella** [comment]
@davidromani :+1:  , lo subes tu o puede subirlo @blackleg directamente? A ver si podemos aprovechar y subimos ya los otros cambios como el menú desplegable por encima del modulo de administración :)

**Comment by davidromani** [comment]
@blackleg cuando haya más cambios realizados
@francesccasadella lo subo yo cuando haya más cambios

**Comment by francesccasadella** [comment]
@davidromani OK para subir a producción :)

**Comment by pr3ssh** [comment]
Esta *issue* sigue abierta pero la veo altamente comentada, desarrollada y desplegada en producción. La cierro.
