### ISSUE TITLE
[Limpieza] Mod following

### ISSUE THREAD

**Issue by blackleg** [Som-Energia/plataforma#52]
El mod following se usa? Es para la version 1.7 y solo añade traducciones.

**Comment by blackleg** [comment]
@Som-Energia/plataforma Se podría eliminar del repositorio? 
Esta activado en el servidor?

**Comment by pr3ssh** [comment]
@Som-Energia/plataforma Sí, está activo. @francesccasadella Recuerdas si se está usando para algo?

**Comment by blackleg** [comment]
Está activado, pero no hace ninguna función, el mod es solo un fichero de idioma para sobre escribir algún texto, pero solo en inglés.

**Comment by francesccasadella** [comment]
entiendo que lo eliminamos en la plataforma 2 y a ver si explota algo :)

2016-11-02 14:36 GMT+01:00 hectorespert <notifications@github.com>:

**Comment by blackleg** [comment]
No creo que explote nada, es un mod que sobre escribe algunos textos en ingles para usar un lenguaje mas parecido a twitter. 
Pero al único idioma que afecta es al inglés,  y no afecta a la base de datos. 
![Readme mod following](https://github.com/Som-Energia/plataforma/blob/master/mod/following/README)
![Archivo con los cambios en el idioma](https://github.com/Som-Energia/plataforma/blob/master/mod/following/languages/en.php)

**Comment by francesccasadella** [comment]
ok :)

2016-11-02 22:38 GMT+01:00 hectorespert <notifications@github.com>:

**Comment by blackleg** [comment]
@Som-Energia/plataforma Eliminaré el mod al final ya que no aporta nada
