### ISSUE TITLE
Que el color de los links del texto destaque más. 

### ISSUE THREAD

**Issue by francesccasadella** [Som-Energia/plataforma#6]

**Comment by blackleg** [comment]
¿Que textos?

**Comment by davidromani** [comment]
@francesccasadella puedes explicar mejor la tarea a @blackleg?

**Comment by francesccasadella** [comment]
@blackleg nos referimos a cuando pones un hipervinculo en un comentario o dentro de cualquier texto de la plataforma. El color que identifica que ese texto es difícil de reconocer y suele pasar desapercibido. He aclarado tu duda?

**Comment by blackleg** [comment]
![](http://www.blackleg.es/images/somenergia/links.png)

Los link verdes? De que color los queréis?

**Comment by francesccasadella** [comment]
@blackleg como aparecen en la captura que adjuntas se ven perfectos :)

**Comment by blackleg** [comment]
La captura es de como me aparecen los links en la versión actual de la plataforma.

No he modificado nada.

**Comment by francesccasadella** [comment]
Ei, pues alguien debe haberlo cambiado porque este verano estaban en color gris. Entiendo que ya podemos cerrar el issue.

**Comment by pr3ssh** [comment]
Hola! Así los veo yo en Firefox con Linux. Supongo que está la tarea lsita para ser cerrada (@francesccasadella).

![screenshot from 2016-01-04 10 23 51](https://cloud.githubusercontent.com/assets/404339/12086767/6633a16c-b2cd-11e5-840e-56f1c211e77a.png)

**Comment by francesccasadella** [comment]
Hola @pr3ssh , con OSX y Chrome yo los veo así. Si no se ponen los links en bold a veces me pasan desapercibidos, a lo mejor podemos poner un tono de verde más claro para que destaquen mas los links del resto de texto? Por ejemplo como el color verde del título de la discusión.  
<img width="827" alt="captura de pantalla 2016-01-05 a les 10 22 30" src="https://cloud.githubusercontent.com/assets/7600601/12111541/6c3d8d74-b396-11e5-8849-4d567b05ef62.png">

**Comment by pr3ssh** [comment]
@francesccasadella de acuerdo. Lo que yo veía genial era por el hecho de que tú los habias puesto en negrita (fallo mio). Hacemos eso.

**READAPTACIÓN DE TAREA:
Poner los links en los comentarios del mismo color verde de los títulos para que destaquen más.**

**Comment by francesccasadella** [comment]
:+1:

**Comment by francesccasadella** [comment]
le he puesto etiqueta "deployed on stagging", está subido a devel o le debería haber puesto "deployed_pending"? Disculpad la pregunta tonta pero se puede ver fácilmente desde Github si el issue se ha subido o no a stagging? ( @pr3ssh @davidromani )

**Comment by davidromani** [comment]
@francesccasadella lo has hecho bien, està subido a plataforma2, por lo tanto el label correcto (de momento) es deployed_on_stagging.

"Esta subido a devel" solamente indica que Enreda ha hecho cambios en el código que considera adecuados de compartir a GitHub. No te preocupes por las ramas devel-master, es cosa nuestra.

**Comment by francesccasadella** [comment]
@davidromani issue color links OK para subir a producción! ( @pablovg2 @pr3ssh )
una pregunta, porqué en el entorno DEVEL se repite el título de la discusión 3 veces y en PRODUCCIÓN solo dos veces? Está mejor en producción. 
pequeña mejora: si no da mucho trabajo, alinear verticalmente el espacio indicado en el punto 2 de esta captura de pantalla: 
![captura_de_pantalla_2016-01-21_a_les_18_57_48](https://cloud.githubusercontent.com/assets/7600601/12489741/112b581a-c072-11e5-89c5-56aa82adb543.jpg)
