### ISSUE TITLE
[Limpieza] Mod notifications_tools

### ISSUE THREAD

**Issue by blackleg** [Som-Energia/plataforma#61]
@pr3ssh @francesccasadella Este mod se esta usando en producción? 
En plataforma2 no esta activado.
Si no se usa, se podría eliminar del código, ya que da problemas con otros mods al estar activado y por defecto se encuentra activado.

**Comment by francesccasadella** [comment]
@blackleg mejor que te respondan @pr3ssh o @pablovg2 o @joseEnrique saludos

**Comment by blackleg** [comment]
@Som-Energia/plataforma @pr3ssh @pablovg2 @joseEnrique Se podría eliminar del repositorio?
Esta activado en el servidor?

**Comment by blackleg** [comment]
Se elimina en la actualización 1.8.20
