### ISSUE TITLE
[Limpieza] Mod proposals y assemblies

### ISSUE THREAD

**Issue by blackleg** [Som-Energia/plataforma#67]
@Som-Energia/plataforma Uno de los mods activados en la plataforma es el de proposals ( Decisiones ).
Creo que es como un sistema de votaciones. 
¿Se usa este mod? ¿Interesaría mantener este mod o se podría "eliminar"? 

El otro es el de assemblies (Asambleas). ¿Se usa este mod? ¿Interesaría mantener este mod o se podría "eliminar"?

Los dos mods, no tienen actualizaciones a partir de la versión 1.8 y aunque se podrían mantener, tendríamos que encargarnos de la compatibilidad con las nuevas versiones.

**Comment by francesccasadella** [comment]
Aprox hay un 10% de grupos que utilizan y tienen bastante historial de asambleas y decisiones, se deberian mantener o migrar manualmente de algun modo o similar.

**Comment by blackleg** [comment]
@francesccasadella Solo es por saber si se utilizan o no. Por ir limpiando un poco el bosque e ir buscando información sobre ellos.
