### ISSUE TITLE
[Mejora] Plugin Menciones Elgg

### ISSUE THREAD

**Issue by blackleg** [Som-Energia/plataforma#68]
@francesccasadella @pr3ssh 
Una mejora que creo que podría ser interesante, en especial para el proceso participativo.
Es un plugin para añadir menciones @elnombredealguien en las conversaciones y que este usuario, reciba notificaciones. [Mod mentions](https://github.com/Elgg/mentions/tree/1.8)

**Comment by francesccasadella** [comment]
@blackleg parece interesante, lo puedes añadir directamente?

**Comment by blackleg** [comment]
@francesccasadella Directamente donde?

**Comment by francesccasadella** [comment]
@blackleg tienes razón, supongo que tocará primero añadirlo en la plataforma2, testear que funciona y luego notificar a @pr3ssh para que puedan añadirlo a producción

**Comment by blackleg** [comment]
@francesccasadella @pr3ssh He creado la rama https://github.com/Som-Energia/plataforma/tree/mentions con el plugin para poder probarlo en plataforma2.

**Comment by francesccasadella** [comment]
@blackleg para probarlo puedo entrar directo a la plataforma2, meterme en un debate, mencionar a un usuario y ver si ya funciona? o hay que hacer algun otro deployment, activación desde el panel de administración o similar? gracias :)

**Comment by blackleg** [comment]
@francesccasadella Habria que actualizar antes plataforma 2 y activarlo.

**Comment by blackleg** [comment]
@francesccasadella ¿Podria tener acceso a plataforma2 para actualizarla al código actual?

**Comment by pr3ssh** [comment]
@blackleg @francesccasadella  Estaba ahora mismo actualizando plataforma2 que estaba desactualizada desde abril. Qué hago? La conecto a esta rama para probar este módulo? O la anclamos a la rama de migración de Elgg que creó @blackleg ?

**Comment by blackleg** [comment]
Actualizar primero a esta rama, para probar primero este modulo y este otro: https://github.com/Som-Energia/plataforma/issues/68
Luego ya se cambiará a la rama de migración, por que una de las cosas que habría que probar en plataforma2 es el cambio del la versión actual a la 1.8.20.

**Comment by pr3ssh** [comment]
@blackleg Acabo de actualizar plataforma2 a esta rama y activar el módudo pero no sé ahora mismo cómo sería el funcionamiento... es escribiendo un arroba y el nombre en cualquier caja de texto (del foro por ejemplo)?

**Comment by blackleg** [comment]
@pr3ssh creo que si

**Comment by pr3ssh** [comment]
@blackleg  Ya va! Es muy funcional. @francesccasadella puedes probarlo para mergear la rama si os gusta?

**Comment by blackleg** [comment]
@francesccasadella @pr3ssh ¿ Costaría mucho borrar la base de datos y la carpeta de datos de plataforma2, y cargar una copia actual de la plataforma ?,.
Para luego hacer la prueba de migración, con una copia lo mas parecida a la de producción.

**Comment by pr3ssh** [comment]
@blackleg Los usuarios de plataforma2 son distintos a plataforma eso si. Pero si, se podria hacer. Coger la bd de plataforma y pasarla junot con los data a plataforma2 y meterle a ésta el master de código. @francesccasadella tú mandas ;)

**Comment by francesccasadella** [comment]
@blackleg @pr3ssh siento el retraso, testeado y genial este módulo, con ganas de verlo activo ya en producción!

**Comment by francesccasadella** [comment]
@pr3ssh adelante con la transferencia hacia plataforma2, entiendo que no os va a ocupar muchas horas y con esto  @blackleg puede hacer un test más real de actualización del elgg. Saludos

**Comment by pr3ssh** [comment]
Lo merge a stagging, devel y master y podo la rama.

**Comment by francesccasadella** [comment]
@pr3ssh así pues ya está activo el módulo de menciones en producción?
