### ISSUE TITLE
Eliminar Mod threads, comentarios en hilo.

### ISSUE THREAD

**Issue by blackleg** [Som-Energia/plataforma#69]
@Som-Energia/plataforma No se si abrir aquí este pequeño debate o directamente en la plataforma.

Uno de los plugins que hay instalados en la plataforma, es threads, que hace que en una discusión las respuestas se muestren como las raíces de una planta, por poner un ejemplo.

[Conversación actual plataforma](https://plataforma.somenergia.coop/discussion/view/175013/desarrollo-plataforma)

Personalmente, como usuario, acostumbrado a facebook, twitter o foros donde se muestra los mensajes seguidos, me resulta un poco complicado seguir las conversaciones. 
Por ejemplo, para comentar alguna cuestión o sugerirla, cuesta encontrar el hilo al que responder.

En plataforma2 no esta activado el plugin por ahora, y se muestran con el formato por defecto en Elgg.
[Así se ven en Plataforma2](https://plataforma2.somenergia.coop/discussion/view/69534/compartir-fuentes-de-informacion-en-la-plataforma)

Me gustaría saber que preferiría la gente, comentarios en hilos o seguidos. 
Para mirar de actualizar y mantener el mod threads, o prepararlo para desactivarlo en un futuro.
Actualmente, si se desactiva, se pierden los comentarios que se han generado con ese mod.

**Comment by CristianRubioRodeja** [comment]
Personalmente, me gusta que las respuestas se vayan anidando tipo árbol o raíces de una planta como dices. También es cierto que no todos los usuarios entienden este concepto y no responden en el lugar correcto, se acaba mezclando todo y se llegan a encontrar respuestas sin sentido en el lugar donde las encuentras.
Creo que será más operativo que las respuestas no se aniden y vayan todas seguidas una tras otra, los usuarios suelen hacer referencia al mensaje al que se refieren trabajando de esta forma
saludos

**Comment by francesccasadella** [comment]
a mi también me gustan más tipo árbol aunque entiendo que es más fácil una
debajo de la otra y si algo le falta a esta plataforma es simplificación :)

2016-11-16 9:25 GMT+01:00 CristianRubioRodeja <notifications@github.com>:

**Comment by blackleg** [comment]
@Som-Energia/plataforma Cierro la issue, seguiremos con el mod activo en la versión 1.9.

**Comment by blackleg** [comment]
@Som-Energia/plataforma Rama con las modificaciones para intentar quitar el mod threads, sin perder los debates de los grupos. [issue/69](https://github.com/Som-Energia/plataforma/tree/issue/69)

Faltaría testearlo mas a fondo y que alguien lo repasara por si me he dejado algo por hacer.
Una vez actualizada la plataforma a la versión 1.12.15, se podría aplicar el cambio.

**Comment by francesccasadella** [comment]
@blackleg en mi caso mejor lo testeo ya en la plataforma2

**Comment by blackleg** [comment]
@francesccasadella No está disponible en plataforma2, si desactivas el mod threads los comentarios en los debates de los grupos no se muestran. 

En los cambios de la rama [issue/69](https://github.com/Som-Energia/plataforma/tree/issue/69) se ejecuta un script al desactivar el mod threads y actualizar la plataforma para que convierta los comentarios guardados por el mod threads en comentarios por defecto de Elgg.

**Comment by francesccasadella** [comment]
@blackleg impresionante. Además, supongo que si en nuevas versiones de Elgg quitaron los comentarios tipo arbol fue por algo.

**Comment by blackleg** [comment]
@francesccasadella Elgg no tiene comentarios tipo árbol por defecto, no sé si en futuras versiones los tendrá.
En nuestro caso los comentarios de ese estilo los genera el mod [threads](https://github.com/lorea/threads).
