### ISSUE TITLE
Instalar plug-in Google Drive

### ISSUE THREAD

**Issue by francesccasadella** [Som-Energia/plataforma#7]
Revisaremos qué funcionalidades ofrece. Ver si se puede poner un límite a la subida de archivos. Una vez visto que funciona correctamente se podría desactivar el módulo actual de subida de archivos.
+info: http://blog.arvixe.com/how-to-integrate-google-drive-with-elgg-1-8/

**Comment by pablovg2** [comment]
Hola @francesccasadella hemos revisado la doc del plugin y lo hemos instalado. El funcionamiento del plugin lo único que permite es mostrar mediante widget el contenido de una carpeta de una única cuenta de Google Drive, en la página del perfil de usuario.

No genera un sistema independiente o alternativa de subida de ficheros. 

Si la idea era remplazar el sistema de subida de ficheros, este plugin no lo permite.

**Comment by francesccasadella** [comment]
Hola @pablovg2 , ok,  te he mandado invitación de hangout para revisar el plug-in en directo, básicamente ver si seria posible hacer una carpeta en Google Drive llamada "Plataforma" con la posibilidad de ir creando un sistema de subcarpetas, por ejemplo una para cada grupo, que cuelguen de ahí. Es decir, si el pluguin está limitado a una única carpeta, permite crear/visualizar subcarpetas dentro de esa carpeta?

**Comment by pablovg2** [comment]
@francesccasadella el plugin no llega a mostrar las carpetas de GDrive porque tiene un error con la autenticación, pero más o menos sería como esta img: https://elgg.org/plugins/879222/icons/1153686.jpg

El problema, que vemos es que el plugin no se actualiza desde hace bastante tiempo y hay bastantes comentario con problemas con el plugin, https://elgg.org/plugins/1153684/releases/0.1 Nosotros después de instalarlo y configurarlo, hemos encontrado varios errores con la API de Drive habría que ver si se pueden solucionar. 

En cualquier caso el plugin solo permite mostrar en una caja de widget ficheros, y para eso creo que es mucha mejor solución hacer como con el plugin de google calendar y mostrar una carpeta de Google drive, como aparece en esta página por ejemplo: https://sites.google.com/site/mori79/html-gadgets/how-tos/google-drive#TOC-Folders

Pero este sistema solo tendría sentido para mostrar ficheros para su descarga, no permitiría subir, ni buscar ficheros como hace ahora el sistema de ficheros de elgg.

**Comment by francesccasadella** [comment]
@pablovg2 "no permitiría subir, ni buscar ficheros" a no ser que en la misma caja pusiéramos un botón  con el enlace hacia esa carpeta con los permisos de subida abiertos en el Drive. Así pues, propongo hacer como con el plugin de google calendar, podemos tomar el "Grupo Sobre la Plataforma" para experimentar con este nuevo widget ahí. 

Enlace a la carpeta de Google Drive creada para el efecto: 
https://drive.google.com/folderview?id=0B3CsItFj_3zadEMwOUp1b1BoZkk&usp=sharing

**Comment by pablovg2** [comment]
@francesccasadella vale, vamos a programar un plugin similar al de google Calendar para mostrar una carpeta de Gogole Drive y lo probamos.

**Comment by blackleg** [comment]
@pablovg2 Si tenéis alguna duda con el plugin del calendar preguntarme.

**Comment by pablovg2** [comment]
Hola, 
Ya he comiteado un plugin para poder embeber un directorio de Google Drive. Para configurarlo hay que indicarle el ID del directorio y el tipo de vista, grid o lista.  Adjunto una captura para que lo veáis. 

![captura de pantalla de 2016-01-20 10 36 38](https://cloud.githubusercontent.com/assets/322535/12444999/2019be18-bf62-11e5-8249-948b92d4c20b.png)

**Comment by davidromani** [comment]
@pablovg2 ya he subido los cambios en stagging (plataforma2.somenergia.coop). También he activado el plugin. @francesccasadella necessito el ID del GDrive que quieres vincular.

**Comment by francesccasadella** [comment]
@davidromani , el ID del folder era: 0B3CsItFj_3zadEMwOUp1b1BoZkk , va bien? ( @pablovg2 )

**Comment by francesccasadella** [comment]
@pablovg2 no entiendo, para visualizar este plug-in tengo que ir al menú "ficheros", la idea era que el widget o plugin fuera visualizable desde el Grupo de Soporte a la Plataforma y no veo como activarlo ahí. adjunto capturas
![captura_de_pantalla_2016-01-21_a_les_17_10_19](https://cloud.githubusercontent.com/assets/7600601/12487029/a91663de-c065-11e5-9a4c-66472a470bdd.jpg)
![captura_de_pantalla_2016-01-21_a_les_17_31_04 2](https://cloud.githubusercontent.com/assets/7600601/12487028/a9161a3c-c065-11e5-8791-805b92433713.jpg)

**Comment by pablovg2** [comment]
@francesccasadella le damos una vuelta, porque el plugin sigue la misma lógica de funcionamiento que el plugin de Calendar. Lo que podemos ver es que se añada un enlace en el menú derecho vertical a la página de la vista embebida con los ficheros. Pero no se podrá implementar mucha funcionalidad más, porque el plugin lo que hace es embeber el listado de ficheros de drive únicamente.

**Comment by francesccasadella** [comment]
@pablovg2 ok, adelante. si se puede poner una caja tipo embed "Miembros del grupo" en el menú lateral derecho estaría bien, sino puede ser un link tipo "Ficheros en Google Drive" seria suficiente. Estaría bien poder ponerlo como widget en la parte central.

**Comment by pablovg2** [comment]
@francesccasadella le he dado varias vueltas a ver como quedaría como widget, pero no salía nada bien, al final lo hemos dejado como un enlace en el menú de la derecha.

**Comment by francesccasadella** [comment]
@pablovg2 ok! Manda captura para ver como queda plz

**Comment by pablovg2** [comment]
![captura de pantalla de 2016-02-10 10 05 05](https://cloud.githubusercontent.com/assets/322535/12942820/d0315c12-cfdd-11e5-8034-4c46f61ba630.png)

El enlace: Ficheros en google Drive

**Comment by francesccasadella** [comment]
@pablovg2 ok, aún no lo puedo ver en la plataforma2, entiendo que @davidromani ya lo subirá esta semana.

**Comment by francesccasadella** [comment]
@pablovg2 interesante, se pueden crear carpetas dentro de la misma carpeta, podríamos tener una carpeta para cada grupo que lo quisiera...  ¿habría algún modo fácil de poner un módulo de comentarios al pie de esta página por si alguien tiene dudas sobre la gestión? 

![captura_de_pantalla_2016-02-23_a_les_1_57_37](https://cloud.githubusercontent.com/assets/7600601/13238160/50ee58c6-d9d1-11e5-9c87-83db8f4d72e6.jpg)

**Comment by pablovg2** [comment]
@francesccasadella lo de poner una carpeta a cada grupo lo veo bastante complicado, porque solo hay un elemento de configuración que es el que determina el directorio de Drive que se comparte. 

Y lo de poner comentaros asociados a esa página, creo que por lo que conozco de Elgg al no ser una entidad propia (comentarios o páginas) sino una forma de listar un contenido emebebido no es posible o al menos es bastante complejo.

**Comment by francesccasadella** [comment]
@pablovg2 ok, ya podéis subir mejora actual a produccion. Ya veremos como vamos avanzando segun necesidades que vayan saliendo. El Drive permite crear una carpeta publica y editable para tod@s asi que quien quisiera leer con la plataforma suficiente pero entrando en el Drive quien quiera podria escribir y crear carpetas nuevas de un modo colaborativo, sin necesidad que hagáis ninguna otra modificacion.

**Comment by pablovg2** [comment]
Ok, entonces podemos cerrar este ticket. Correcto?
