### ISSUE TITLE
Mod SimplePie RSS Feed Integrator

### ISSUE THREAD

**Issue by blackleg** [Som-Energia/plataforma#71]
[SimplePie RSS Feed Integrator](https://elgg.org/plugins/384545) 
Añade un widget para el protocolo RSS.
Este mod esta activo en la plataforma y no pertenece al núcleo de Elgg.
¿Se podría eliminar para ir simplificando la plataforma? 
Mi idea sería desactivarlo antes de actualizar a la 1.9.7

**Comment by francesccasadella** [comment]
@blackleg ok a eliminarlo para simplificar, además diria que su funcionamiento no era el óptimo. 

Más adelante con el RSS del Blog de Som Energia se podrian crear modulos de feeds para distintas categorias de notícias y etiquetas dentro de la plataforma, aunque habría que pensarlo bien antes de ponerse a implementarlo.  Me refiero a estos módulos de feeds del blog como estos que ya hay integrados a medida en distintos puntos de la web: 
<img width="732" alt="captura de pantalla 2016-12-14 a les 13 44 07" src="https://cloud.githubusercontent.com/assets/7600601/21182472/9b0233cc-c203-11e6-8a79-c558dac3e515.png">

**Comment by blackleg** [comment]
@francesccasadella Preparé la eliminación en alguna actualización.
