### ISSUE TITLE
Actualización plataforma 1.8.20

### ISSUE THREAD

**Issue by blackleg** [Som-Energia/plataforma#72]
@Som-Energia/plataforma Creo esta issue para tratar la actualización de la plataforma a la versión [1.8.20](https://github.com/Som-Energia/plataforma/issues/14#issuecomment-267047096)
La issue que contempla las actualizaciones es esta: [Issue 14](https://github.com/Som-Energia/plataforma/issues/14)
La rama de desarrollo de la versión: [upgrade_1_8_20](https://github.com/Som-Energia/plataforma/tree/upgrade_1_8_20)

Notas: 

* La actualización contiene el mod [SomEnergia Translations](https://github.com/Som-Energia/plataforma/issues/73)
* La actualización no contiene los últimos cambios realizados en el mod groups para el proceso participativo.
En concreto el botón de acceso directo al drive con la documentación del proceso. 
Al actualizar la versión del mod, se han sobrescrito los cambios, si veis conveniente que una vez finalizado el proceso, el botón tiene que continuar estando disponible o queréis actualizar la versión antes de finalizar el proceso por que la veis estable, se podría volver a añadir.

**Comment by davidromani** [comment]
Hola @blackleg 

En el archivo README_UPGRADE_1_8_20.md comentas en el punto 4.4 que hay que ejecutar una actualización de base de datos del mod tidypics. Me puedes indicar como lo hago?

Creo que comentamos por teléfono que estava dentro de un script SQL pero ahora mismo no encuentro el archivo...

Gracias.

**Comment by blackleg** [comment]
@davidromani No es un archivo sql. Dentro de el panel de administración de Ellg, en la configuración del mod Tidypics o en el menu de actualizacion de Ellg, saldrá un aviso con un enlace para ejecutar la actualización la base de datos de Tidypics.

**Comment by davidromani** [comment]
@blackleg ok, hecho. Estoy en el último commit de esta rama, la he instalado y configurado en mi entorno local primero. Ahora me encuentro con ha desaparecido el mod/event_calendar 

Es normal?

**Comment by blackleg** [comment]
@davidromani Es normal, eliminé todos los mods que no estaban activados en la copia de la base de datos que recibí. Creo que ese mod ya no está en producción porque se usa el somenergia_calendar.

**Comment by davidromani** [comment]
ok, podemos hacer un hangout esta tarde? @blackleg

**Comment by blackleg** [comment]
@davidromani Si es sobre las 20:30 si

**Comment by davidromani** [comment]
Uff, demasiado tarde, esta semana lo tengo complicado para quedar más tarde de las 19:30h. Podemos quedar otro dia más pronto? (sábado por la mañana también me va bien)

**Comment by blackleg** [comment]
@davidromani Por la tarde a las 4 o 5 podría desde el trabajo

**Comment by francesccasadella** [comment]
@blackleg @davidromani como va el proceso de actualización, alguna novedad? puedo ayudar en algo?

**Comment by blackleg** [comment]
@francesccasadella Hace tiempo que @francesccasadella me comentó de hablar sobre algún problema que tuvo pero no he vuelto a saber nada.

**Comment by davidromani** [comment]
Perdon, fui yo. @blackleg podemos quedar el próximo lunes 20 de febrero sobre las 20:00h en Hangout?

**Comment by blackleg** [comment]
@davidromani Estás perdonado. No hay ningún problema para el lunes.

**Comment by davidromani** [comment]
@blackleg me puedes pasar tu email en privado?

**Comment by blackleg** [comment]
@davidromani Tengo tu email con el dominio flux.cat, es correcto?

**Comment by davidromani** [comment]
sí

**Comment by blackleg** [comment]
@davidromani Te he enviado mi correo

**Comment by blackleg** [comment]
@davidromani Cambio de planes, para el lunes me ha surgido un imprevisto, tendrías algún problema para el martes?

**Comment by davidromani** [comment]
@blackleg en realidad, a mi, me va mejor el miércoles a la misma hora. Es posible? Sino ya me organizo para el martes..

**Comment by blackleg** [comment]
@davidromani Me es imposible el miércoles.

**Comment by davidromani** [comment]
@blackleg ok, pues el martes

**Comment by davidromani** [comment]
@blackleg ahora tengo yo el problema en martes... :-( podemos quedar el jueves?

**Comment by blackleg** [comment]
@davidromani Ningún problema. Este finde o esta tarde también podría.

**Comment by blackleg** [comment]
@francesccasadella Plataforma2 esta actualizada a la versión 1.9.8 y se pueden hacer pruebas.
¿Cuando actualizamos?

@davidromani He solucionado el fallo que daba el mod del calendario en plataforma2.

**Comment by francesccasadella** [comment]
Abierto el hilo en la Plataforma: [https://plataforma.somenergia.coop/discussion/view/202018/plan-de-mejoras-en-la-plataforma-2017](https://plataforma.somenergia.coop/discussion/view/202018/plan-de-mejoras-en-la-plataforma-2017)

Las pruebas realizadas hasta ahora, aunque pocas, parecen tener resultados positivos. 

En la página de inicio de la plataforma2 aparecen algunos avisos en rojo tipo "Deprecated in 1.8, widgets use content display view" que supongo tenéis controlados.

Una duda, la idea es implementar la nueva versión de plataforma2 en el entorno de producción y luego actualizar la plataforma2 a la 1.10 para empezar las pruebas y así sucesivamente?

**Comment by francesccasadella** [comment]
@blackleg @davidromani veo que cuando alguien comenta en un grupo de la plataforma2 las notificaciones las reciben también las personas de ese grupo en la Plataforma1, con lo molesto que esto puede llegar a ser. Tendriamos que desactivarlo cuando antes mejor.

**Comment by blackleg** [comment]
@davidromani @francesccasadella @Som-Energia/plataforma ¿Cuando podemos mirar de subir esta actualización?

**Comment by blackleg** [comment]
@Som-Energia/plataforma La actualización a la versión 1.8.20 esta en la rama devel: https://github.com/Som-Energia/plataforma/commit/ca05ef40b87f706e102f40a17d1794b3533492ff

**Comment by blackleg** [comment]
@Som-Energia/plataforma Plataforma actualizada a la 1.8.20
