### ISSUE TITLE
Comentarios duplicados o triplicados

### ISSUE THREAD

**Issue by francesccasadella** [Som-Energia/plataforma#77]
Suele ocurrir con demasiada frecuencia que aparecen comentarios duplicados o triplicados en la plataforma que además mandan notificaciones duplicadas o triplicadas por email. Habría que intentar averiguar  porqué suceden estos casos y darle solución de algun modo.

**Comment by blackleg** [comment]
@Som-Energia/plataforma Se puede sacar algún tipo de log del fallo?

**Comment by francesccasadella** [comment]
@blackleg  desde el menú de administrador desplegable en el perfil se puede ver un log de la actividad de la persona, no sé si esto puede ayudar, en un minuto los registros van desde la pagina 28 a la 38: 
![captura de pantalla 2017-01-12 a les 10 47 39](https://cloud.githubusercontent.com/assets/7600601/21884718/c197a87e-d8b4-11e6-88dd-c802ad1515b1.png)

**Comment by blackleg** [comment]
@francesccasadella @Som-Energia/plataforma Se podrían sacar los logs de apache en esos momentos, por si se muestra algún fallo de php o similar?
 Algunas ideas:
El mod threads es el que se encarga de los comentarios, en la futura actualización a la versión 1.8.20, el mod se actualiza a la ultima versión disponible que tiene soporte hasta la versión 1.12 de Elgg.

Se podría probar a actualizar el mod Threads ha esta versión para ver si se solucionan los fallos de comentarios duplicados.

**Comment by francesccasadella** [comment]
Buenas, dejo constancia que me acaba de pasar esto del comentario duplicado, em mi caso, me he podido fijar que como iba lento a publicar la respuesta pinché dos veces al botón "responder" lo que en vez de reiniciar el proceso de publicación provocó un comentario doble. seguimos.

**Comment by francesccasadella** [comment]
he realizado el test en la platafora2 y he pulsado 3 veces el botón de "Responder" mientras la plataforma estaba "pensando" y el resultado fue un triplicado del comentario:
![captura de pantalla 2017-03-01 a les 13 29 37](https://cloud.githubusercontent.com/assets/7600601/23460049/6790822a-fe83-11e6-8341-9e4bc2840837.png)

**Comment by francesccasadella** [comment]
si de algun modo se puediera acelerar la velocidad de la plataforma, eso no sucederia. En la plataforma2 he esperado hasta 1 minuto para que terminara de procesar la publicación.

**Comment by blackleg** [comment]
@francesccasadella Solucionado en la futura versión 1.8.20
