### ISSUE TITLE
Dockers Plataforma

### ISSUE THREAD

**Issue by blackleg** [Som-Energia/plataforma#79]
Desarrollo dockers plataforma

**Comment by blackleg** [comment]
@davidromani Aun estás interesado en crear una imagen docker para la plataforma? Creo que me lo comentaste un día.

**Comment by davidromani** [comment]
Sí, pero de momento, sólo para garantizar que los developers teneis el mismo entorno que en producción.

Puedes configurar el dockerfile para estas versiones?
- MySQL 5.7
- Apache 2.4
- PHP 7.0

**Comment by blackleg** [comment]
@davidromani En vez de un solo dockerfile he montado un docker compose con los servicios.
