### ISSUE TITLE
Limitar entradas de los módulos de la página inicial de los grupos.

### ISSUE THREAD

**Issue by francesccasadella** [Som-Energia/plataforma#8]
El objetivo es mejorar la visualización de todos los módulos que hay en un grupo. Ahora mismo los modulos inferiores pueden perder mucha visibilidad.

**Comment by francesccasadella** [comment]
![captura_de_pantalla_2016-01-21_a_les_20_51_33](https://cloud.githubusercontent.com/assets/7600601/12492542/fee045ee-c080-11e5-9e2e-fc44b206af50.jpg)

**Comment by pr3ssh** [comment]
@francesccasadella Intentaría poner los resúmenes más pequeños (menos items) para que quede todo más condensado. Si lo ves ok podemos tirar por esa solución aunque ya te digo que a mi como usuario "no muy activo" ciertos elementos de esta página me aportan poco.

**Comment by pr3ssh** [comment]
@francesccasadella por otro lado he hecho una mejora en la página de inicio del sistema ya que el widget *on the river* aparecía demasiado largo (20 items) y es que los parámetros no se estaban pasando de forma correcta en la llamada a dicho widget. Lo he fijado para que se quede en 7 que creo que es un buen número resumen. Quedaría así:

![screenshot from 2016-02-10 18 54 02](https://cloud.githubusercontent.com/assets/404339/12956672/6d4a5de6-d029-11e5-983b-226484526923.png)

**Comment by pr3ssh** [comment]
Nota: Limitar entradas en el grupo y quitar bloques que estén vacíos.

**Comment by joseEnrique** [comment]
Solo falta ocultar los widgets sin contenido

**Comment by francesccasadella** [comment]
Hola @joseEnrique , no veo las mejoras aplicadas dentro de  plataforma2, a ver si puedes pasar alguna captura donde aparezcan las limitaciones en "on the river" y en los widgets con contenido de las páginas de grupos. Merci

**Comment by joseEnrique** [comment]
![somenergialimit](https://cloud.githubusercontent.com/assets/1654589/14241068/d54424dc-fa49-11e5-8888-86dc482cce59.png)

**Comment by pr3ssh** [comment]
@francesccasadella @davidromani No lo hemos subido aun a la rama stagging porque no está la tarea 100% acabada. Estamos intentando ocultar los widgets que no tienen contenido pero nos estaba costando algo más de lo esperado. Quieres probar esto por separado? Si ves que la tarea puede quedar resuelta con esta solución pues OK y si no seguimos con lo que estábamos.

**Comment by francesccasadella** [comment]
@pr3ssh @joseEnrique con la limitación del contenido ya lo veo bien, referente a los módulos sin contenido, entiendo que pueda ser difícil de automatizar, abrimos otro issue que sea la revisión i desactivación "manual" de los widgets sin contenido de los grupos? Será un trabajo laborioso pero seguro que podremos detectar y listar los widgets que nadie usa para desactivarlos de la plataforma.

**Comment by pr3ssh** [comment]
@francesccasadella Nos parece correcto. Acabamos de subir estos cambios a stagging y crea si puedes otra tarea de revisión para los widgets sin contenido o poco usados.

**Comment by francesccasadella** [comment]
:ok:
