### ISSUE TITLE
Security Vulnerability

### ISSUE THREAD

**Issue by francesccasadella** [Som-Energia/plataforma#81]
Tenemos un tweet que dice esto: 
"Dear @SomEnergia please notify your IT security team about a security vulnerability on your website" 
És este:  https://twitter.com/openbugbounty/status/830415260502810624

¿alguna idea?

**Comment by blackleg** [comment]
@Som-Energia/plataforma @francesccasadella 
No hay muchos detalles: [incidents/212586](https://www.openbugbounty.org/incidents/212586)
Se le puede preguntar a quien ha reportado el aviso: [Alyssa_Herrera](https://www.openbugbounty.org/researchers/Alyssa_Herrera)

Pero me da a mi la sensación de que es una falsa alarma para que contrates al que te ha reportado.

**Comment by blackleg** [comment]
@francesccasadella Esta issue la damos por cerrada?

**Comment by francesccasadella** [comment]
@blackleg por mi Ok a cerrarla

El 11 maig 2017, a les 9:39, hectorespert <notifications@github.com> va escriure:
