### ISSUE TITLE
Que se abran siempre en una pestaña nueva.

### ISSUE THREAD

**Issue by francesccasadella** [Som-Energia/plataforma#9]
Que cuando haces clic para ver un archivo este se abra en una pestaña nueva. Ahora mismo se carga en la misma página y algunos usuarios no pueden volver a la pagina anterior de la plataforma una vez descargado el archivo.

**Comment by pablovg2** [comment]
¿@francesccasadella te refieres al enlace a la página del fichero dónde está el fichero para su descarga o al enlace del fichero para descargar? 

Te adjunto una captura para entenderlo mejor.
![primer_enlace](https://cloud.githubusercontent.com/assets/322535/12448335/86877786-bf75-11e5-823e-1fd7a011431b.png)

**Comment by francesccasadella** [comment]
@pablovg2 en realidad, diría que el "error" que comentó Maribel solo ocurre cuando le das clic al "Segundo enlace" y además el fichero es un archivo PDF, pues en este caso el navegador te carga la visualización del archivo en la misma pestaña, el resto de archivos diría que te los descarga directo sin la previsualizacion. En todo caso, me referia al "Segundo enlace" :)

**Comment by joseEnrique** [comment]
@francesccasadella hemos resuelto el tema que se abra en otra pestaña con el botón de descarga. Para el "segundo enlace" hemos visto que el renderizado del layout del archivo lo hace en el core de elgg. Si se considera una cuestión imprescindible valoramos la modificación.

**Comment by francesccasadella** [comment]
@joseEnrique esperando a que se suba a stagging para revisarlo. cc. @davidromani

**Comment by joseEnrique** [comment]
Subido los cambios a stagging

**Comment by francesccasadella** [comment]
@joseEnrique entro en la plataforma2 > grupo Bienvenida > Archivos del grupo , le doy clic al primer enlace y sigue cargando en la misma pestaña, puedes revisar?
[https://plataforma2.somenergia.coop/file/group/1117/all](https://plataforma2.somenergia.coop/file/group/1117/all)
![captura_de_pantalla_2016-04-04_a_les_11_07_39](https://cloud.githubusercontent.com/assets/7600601/14243404/a9d6c690-fa55-11e5-99b4-3c748e74f7a2.jpg)

**Comment by joseEnrique** [comment]
@francesccasadella esa es la primera pantalla en la que sale el listado de todos los recursos. Una vez que accedes ahí sale la vista del recurso, es ahí donde saldrá el enlace y un botón de "Descargar", de momento solo está modificado ese botón y estamos búsqueda del enlace. Los cambios se están haciendo en stagging y hay que hacer merge a la rama devel para que se produzca los cambios.

**Comment by francesccasadella** [comment]
@joseEnrique ok, espero a que esté en devel.

**Comment by francesccasadella** [comment]
@joseEnrique botón "descargar" con enlace a nueva pestaña OK en staggin, habéis localizado ya el enlace del archivo para que también se abra en nueva pestaña?

**Comment by joseEnrique** [comment]
@francesccasadella enlace modificado. Mañana en el reporte lo comiteamos
